services:
  - type: web
    name: hcp-booking-automation
    runtime: docker
    plan: starter
    region: oregon
    buildCommand: docker build -t hcp-booking .
    startCommand: npm start
    envVars:
      - key: PORT
        value: 8080
      - key: HEADLESS
        value: "0"  # Virtual display + headed mode for email confirmations
      - key: NODE_ENV
        value: production
      # Cloud Browser Service (CloudBrowser AI) - bypasses all detection!
      - key: CLOUD_BROWSER_URL
        value: "ws://browser.cloudbrowser.ai/35/devtools/browser/1158e9a4-6640-4eec-b71a-90cd40a916c4"
      - key: CLOUD_BROWSER_TOKEN  
        value: "849f670a-57c3-4b1a-8fb8-949fe3c3265a"
    # You'll need to set these in Render dashboard:
    # - WEBHOOK_SECRET
    # - RUNNER_URL  
    # - RUNNER_AUTH
    # - BROWSERCAT_API_KEY (if using Browsercat)
    # - SENTRY_DSN (for error tracking)
    
    # Disk storage for screenshots and temporary files
    disk:
      name: screenshots
      mountPath: /app/screenshots
      sizeGB: 1
      
    # Health check endpoint
    healthCheckPath: /
    
    # Auto-deploy from main branch
    autoDeploy: true
    
    # Scale configuration
    numInstances: 1
    
    # Build settings
    dockerfilePath: ./Dockerfile
    dockerContext: ./
